### ISSUE TITLE
Add instruction for WSL users

### ISSUE THREAD

**Issue by na4zagin3** [gfngfn/SATySFi#115]
As reported in https://github.com/ocaml/opam-repository/issues/12050#issuecomment-393478072, we have to disable bubblewrap to use OPAM on WSL. I believe that problem confuses many newbies who try to install SATySFi on WSL. (e.g., https://twitter.com/puripuri2100/status/1053254602273959936)

It’d better to have a notice or an instruction for WSL users.

**Comment by nekketsuuu** [comment]
Ubuntu 16.04 also lacks bubblewrap. See ocaml/opam#3424 for details, or read [my short post here](https://nekketsuuu.github.io/entries/2018/10/09/bwrap-for-opam2.html) in Japanese.
