### ISSUE TITLE
Primitives that can not be used in text-mode.

### ISSUE THREAD

**Issue by puripuri2100** [gfngfn/SATySFi#141]
This primitives can not be used in text-mode of SATySFi .  Is this a bug?

- `*'`
- `/'`
- `+'`
- `-'`

# Environment

- SATySFi commit [c859e15245bbf5fb37150e9dd2637a440d5f63a6](https://github.com/gfngfn/SATySFi/commit/c859e15245bbf5fb37150e9dd2637a440d5f63a6)
- ubuntu 18.04.1
- OCaml 4.06.0 + OPAM 2.0.1

# Example

file name : `test.saty`

```
let document bt =
  let tinfo = get-initial-text-info () in
    stringify-block tinfo bt


let-block tinfo +p it = stringify-inline tinfo it

let-inline \test =
  let fuga = 120.5mm /' 1pt in
    {test}

in

document '<
  +p{hoge\test;}
>
```

compile :

```
satysfi --text-mode "text" test.saty -o test.txt
```

error log :

```
satysfi --text-mode "text" test.saty -o test.txt
 ---- ---- ---- ----
  target file: 'test.txt'
  dump file: 'test.satysfi-aux' (already exists)
  parsing 'test.saty' ...
 ---- ---- ---- ----
  reading 'test.saty' ...
! [Type Error] at "test.saty", line 9, characters 21-23:
    undefined variable '/''.
```

**Comment by puripuri2100** [comment]
Used to convert length type to string type.

```
let show-length len = show-float (len /' 1pt) ^ `pt`
```

**Comment by gfngfn** [comment]
Modified by the following commit: 59aedacb4522e4eee3526637278fd25660d6eb22.
