### ISSUE TITLE
Per-project font configuration

### ISSUE THREAD

**Issue by nyuichi** [gfngfn/SATySFi#154]
Currently there is no means to distribute .saty files together with custom font settings (fonts.satysfi-hash).
It is cumbersome to distribute a shell script that modifies say `~/.satysfi/local/hash` whenever I share .saty files portably.
It is helpful if satysfi uses custom hash/fonts when I put them in a git repository.
I think one way to do so is to add the current directory to satysfi's search path.
That is, satysfi will search for configs "./", "~/.satysfi", "/usr/local/share/satysfi", "/usr/share/satysfi" in this order.
Another possible idea is add a command line option like `-C path`, analogous to `make -C path` or `gcc -I path`.
My preference is the latter, because it will be much easier to write a portable Makefile that executes satysfi.

**Comment by na4zagin3** [comment]
@nyuichi FYI, [Satyrographos](https://github.com/na4zagin3/satyrographos) makes it possible to distribute hash files including fonts.satysfi-hash. Also, you can set up lib root at any location like this.

```
$ ls local-package/fonts/fonts.satysfi-hash # assumes you files under local-package directory
$ export SATYSFI_RUNTIME="$PWD/satysfilib # at any location you like
$ SATYROGRAPHOS_EXPERIMENTAL=1  satyrographos package add local-package-for-some-project local-package
$ satyrographos install
$ satysfi your-document.saty -o your-document.pdf
```

**Comment by nyuichi** [comment]
Ah I didn't know your satyrographos can manage fonts as well (I knew there was a package manager for satysfi, though).
Can I use satyrographos like this?

```console
$ ls -a
article.saty
satysfi-project-description  # includes font/package dependency description
$ satyrographos init
.satysfi/  # automatically set up
article.saty
satysfi-project-description
$ satyrographos build
$ ls article.pdf
article.pdf
```

**Comment by na4zagin3** [comment]
@nyuichi Not yet. Hopefully you will soon :slightly_smiling_face:
It’s one of the goal of Satyrographos and I am still developing toward it.

At least, the current Satyrographos can
- compose the distributed standard library and user libraries; and install them to arbitrary location
- merges hash files during composition
- get user libraries from opam registory (under `$(opam config var share)/satysfi`) and locally installed libraries (under `~/.satyrographos/packages`) with `satyrographos pin add NAME DIR`.
- optionally generate fonts.satysfi-hash gathering fonts installed in the system with fontconfig.
