### ISSUE TITLE
Unable to load `DejaVuSansMono.ttf` (GPOS-related error)

### ISSUE THREAD

**Issue by nyuichi** [gfngfn/SATySFi#156]
I got an error like the following when I was trying to use the [DejaVu Sans Mono](https://dejavu-fonts.github.io) font (version 2.37):

```console
$ satysfi test.saty
[...]
  evaluating texts ...
! [Error] font file 'DejaVuSansMono.ttf' is broken;
      Unknown version (1BD) in table 'GPOS'; get_mark_table
```

**Comment by sakas--** [comment]
I had the same issue before when I tried to use `DejavuSansMono`.
When I had a look at this bug, I found that this is a bug of  [otfm package](https://github.com/gfngfn/otfm/) (note that this fork is way ahead of the original repo), also maintained by @gfngfn, so it might be better to open an issue there.
