### ISSUE TITLE
Unable to load `inconsolatalgc.ttf` (GSUB-related error)

### ISSUE THREAD

**Issue by nyuichi** [gfngfn/SATySFi#157]
(Probably related to #156)

Satysfi throws an error when I try to use the [Inconsolata LGC](https://github.com/DeLaGuardo/Inconsolata-LGC) font.

```console
$ satysfi test.saty
[...]
! [Error] font file 'inconsolatalgc.ttf' is broken;
      Unexpected end of input in table 'GSUB'; get_ligature_table
```

**Comment by gfngfn** [comment]
Thank you for reporting. The bug was fixed by [this commit for the forked version of `otfm`](https://github.com/gfngfn/otfm/commit/4ba879d41db0a964fad28aaf14073246e77bea91). This change was reflected by dd181b2c988c593c9d8e70933125d57a2f6b853b and will be merged into `master` soon.

**Comment by nyuichi** [comment]
@gfngfn Thank you for the quick response!
BTW, does your fix mean that #156 is fixed as well?

**Comment by gfngfn** [comment]
@nyuichi Unfortunately the error #156 still remains… It seems due to an independent bug of the forked version of `otfm`.

**Comment by nyuichi** [comment]
@gfngfn Thank you for the clarification! I will do anything I can help you with about this, so please tell me then.
