### ISSUE TITLE
`@import` is don't work in text-mode

### ISSUE THREAD

**Issue by puripuri2100** [gfngfn/SATySFi#162]
`@import` command is don't accept `.satyh-*` and `.satyg` file .

input :

```
@import local

document '<+p{hoge}>
```

error message :

```
! [Error] /home/puripuri2100/SATySFi-test/local.sath : No such file or directory
```

**Comment by gfngfn** [comment]
The required feature is supported as of https://github.com/gfngfn/SATySFi/commit/0326b268e6afc516e9eb97f1a06de07ed07c5d3b. Thanks for suggestion.
