### ISSUE TITLE
Fix post-install message

### ISSUE THREAD

**Issue by na4zagin3** [gfngfn/SATySFi#18]
### Problem & Proposal
The post-install message introduced by ab3f781 is wrong. `$(PREFIX_LIB)` must be replaced by a real path.

```
Please set SATYSFI_LIB_ROOT. You may want to add the following line to ~/.bashrc"
export SATYSFI_LIB_ROOT=$(PREFIX_LIB)/lib-satysfi"
```

### Environment
macOS 10.13.2
OCaml 4.05.0 + OPAM 1.2.2
SATySFi commit bc30f33

### Workaround
- Nothing.

**Comment by nekketsuuu** [comment]
I think this issue is already resolved because SATYSFI_LIB_ROOT is now deprecated.

**Comment by na4zagin3** [comment]
@nekketsuuu You're right. Closing.
