### ISSUE TITLE
Short-circuit evaluation for (&&)

### ISSUE THREAD

**Issue by nyuichi** [gfngfn/SATySFi#186]
The current implementation of the conjunction binary operator (&&) does not short-circuit arguments:

```
let-mutable x <- 0
let _ = false && (let () = x <- 1 in true)
!x  %=> 1
```

Is this behavior intentional?

**Comment by gfngfn** [comment]
This behavior is intended. `&&` is just an ordinary function of type `bool -> bool -> bool`.

**Comment by nyuichi** [comment]
Is there a plan to add a new operator that performs short-circuit evaluation?

**Comment by gfngfn** [comment]
Do you have a strong reason for adding short-circuit variant of `&&`? IMHO it seems sufficient to just use `(&&-) : bool -> (unit -> bool) -> bool` defined as follows:

```
let (&&-) b k = if b then true else k ()
```

**Comment by nyuichi** [comment]
I am writing a lexer/parser library for satysfi and making heavy use of an idiom like `if i < string-length s && some-pred (string-sub s i 1) then …`.
Without short-circuit it evaluates the second condition before the array index validation is performed and simply raises a runtime error.
I don’t think this is a rare case. The same could happen if I was writing another library that uses Array or hashtable.

> 2019/07/11 16:30、T. Suwa <notifications@github.com>のメール:
> 
> Do you have a strong reason for adding short-circuit variant of &&? IMHO it seems sufficient to just use (&&-) : bool -> (unit -> bool) -> bool defined as follows:
> 
> let (&&-) b k = if b then true else k ()
I think one big goal of satysfi is ``typesetting without super programming techniques’’, which of course TeX fails to accomplish.
I do not think restricting expressive power contributes to this aim.
It can rather trigger ``super satysfi programming techniques.''

If you are not willing to stop treating binary operators all uniformly, what about introducing keywords like `and` and `or` as in python?
Or, is it possible to use the new metaprogramming framework to define such a metalevel function instead?

**Comment by elpinal** [comment]
> Or, is it possible to use the new metaprogramming framework to define such a metalevel function instead?

`a.satyh`:
```
@stage: 0

let (&&&) b1 b2 = &(if ~b1 then ~b2 else false)
```

`b.satyh`:
```
@import: a

let-mutable x <- 0
let _ = ~(&false &&& &(let () = x <- 1 in true))
let z = !x   %=> 0
```

A bit cumbersome, though.

**Comment by nyuichi** [comment]
> 2019/07/11 20:52、El Pin Al <notifications@github.com>のメール:
> 
> Or, is it possible to use the new metaprogramming framework to define such a metalevel function instead?
> 
> a.satyh:
> 
> @stage: 0
> 
> let (&&&) b1 b2 = &(if ~b1 then ~b2 else false)
> b.satyh:
> 
> @import: a
> 
> let-mutable x <- 0
> let _ = ~(&false &&& &(let () = x <- 1 in true))
> let z = !x   %=> 0
> A bit cumbersome, though.
> 
> 

That’s very helpful.
And that’s not that cumbersome I think, at least for my purpose.
Thanks a lot!
