### ISSUE TITLE
Is Travis CI testing NOT working?

### ISSUE THREAD

**Issue by y-yu** [gfngfn/SATySFi#224]
- Travis CI status has not been shown 🤔 
- ![image](https://user-images.githubusercontent.com/612043/77818026-94526800-7112-11ea-88b6-e98947203ea1.png)

**Comment by y-yu** [comment]
I encountered the same thing in https://github.com/rust-lang-ja/book-ja-pdf/pull/5 . And it was solved by this way 👇 

1. Access to the [GitHub applications admin page](https://github.com/settings/applications)
    - And look at `Authorized OAuth Apps` tab
2. Look for the `Travis CI for Open Source` in the tab
    - ![image](https://user-images.githubusercontent.com/612043/79068763-3a51c500-7d04-11ea-8316-6ebf5a960869.png)
3. Revoke the `Travis CI for Open Source`
    - <img src="https://user-images.githubusercontent.com/612043/79068771-52294900-7d04-11ea-882c-3bb7ecaa4362.png" width="40%"/>
4. Access to https://travis-ci.org/ (NOT travis-ci.**com**) and sign out if you are signed in
    - <img src="https://user-images.githubusercontent.com/612043/79068811-a03e4c80-7d04-11ea-8869-a8f85eae2d4a.png" width="40%"/>
5. Sign in the circle-ci.org by your GitHub account
6. Authorize Circle CI for GitHub again

Good luck!

**Comment by gfngfn** [comment]
I’m sorry for the late response. I performed just now the procedure you had kindly introduced to me!

**Comment by gfngfn** [comment]
Is this sufficient to run CI next time when pushing commits to this repository? I mean I wonder whether I still have another task like activating the connection of this repository and Circle CI.

**Comment by y-yu** [comment]
Sorry, I wrote `circle-ci.org`. It was a mistake!!! I insisted `travis-ci.org`.

**Comment by gfngfn** [comment]
I understand. I signed in `travis-ci.org` just now.

**Comment by gfngfn** [comment]
The CI seems working well. Thank you very much for your kind introduction!

**Comment by y-yu** [comment]
CI is running like that 👉 https://travis-ci.org/github/gfngfn/SATySFi/builds/677166453 but the results are *not* shown from GitHub.... 😇 

![image](https://user-images.githubusercontent.com/612043/79741544-67255e00-833c-11ea-9382-89b46c3e371c.png)

I think that the connection between GitHub and Travis CI has still been broken. Maybe my forked repository name is not`SATySFi`, it is the reason... 🤔why CI results will not be shown.

Sorry I cannot help you for now because I cannot see what happens in detail.... 🙇

**Comment by qnighy** [comment]
travis-ci.org uses the old GitHub statuses API, while travis-ci.com the new checks API. They were originally separated based on open source / commercial distinction, but .com is now open for open source projects and Travis encourages migration from .org. That may be the reason 
the statuses are not shown.

**Comment by y-yu** [comment]
Thanks!  I'm still using [travis-ci.org](https://travis-ci.org) so [travis-ci.org](https://travis-ci.org) haven't gave up to support the latest GitHub API yet, I think... However `Travis encourages migration from .org.` so it would be better to try out [travis-ci.com](https://travis-ci.com) in any case.

**Comment by y-yu** [comment]
We decided to leave from Travis CI for GitHub Actions and it's done by #250 #255 #256.
