### ISSUE TITLE
Missing dependency of uchar

### ISSUE THREAD

**Issue by nekketsuuu** [gfngfn/SATySFi#23]
I noticed that a package [`uchar`](https://opam.ocaml.org/packages/uchar/) is not written in [`opam`](https://github.com/gfngfn/otfm/blob/8f1086ea1773d665cf8e24ecd6c84551e0cc94ed/opam#L16) whereas it's needed for the external package `otfm` ([ref](https://github.com/gfngfn/otfm/blob/8f1086ea1773d665cf8e24ecd6c84551e0cc94ed/opam#L16)). Also, a constraint `"uutf" {>= "1.0.0"}` is missing.

Although `uchar` is unnecessary for OCaml >= 4.03, this should be written in `opam`.
Or, using opam repo (#14) will help.

**Comment by objmagic** [comment]
> Although uchar is unnecessary for OCaml >= 4.03

why is that?

**Comment by nekketsuuu** [comment]
@objmagic I think `uchar` is a compatibility library for OCaml < 4.03. Sorry if I misunderstood.

**Comment by objmagic** [comment]
@nekketsuuu 
Oh I see. you are right. But with #16, we no longer need to specify such dependency.

**Comment by objmagic** [comment]
can be closed via #16

**Comment by nekketsuuu** [comment]
Although `uchar` is unnecessary for OCaml 4.06.0, I don't know it's OK not to write `uchar` in `opam`. The `opam` file of `gfngfn/otfm` says it needs `uchar` to build, and we build `gfngfn/otfm` at the compile time of SATySFi. I think #14 can divide this dependency into each external library.
