### ISSUE TITLE
How can I write multiple lines under \sum ?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [gfngfn/SATySFi#247]
How can I stack multiple lines in math mode, as in the following image?

![\sum_{\substack{i = 1 \\ i \neq k}}^n i^2](https://user-images.githubusercontent.com/47710717/97473661-97565500-198e-11eb-990f-67baf8b2ec84.png)

```tex
\sum_{\substack{i = 1 \\ i \neq k}}^n i^2
```

**Comment by TonalidadeHidrica** [comment]
`\lower` produces smaller text.

**Comment by monaqa** [comment]
Did you try the following code?
```
+math(${
  \sum_{i=1}^n i^2 = k^2 + \lower{\sum_{i=1}^n}{i\neq k} i^2
  });
```

Or, if you don't like that `i=1` and `i\neq k` are written far apart, you can write like this:

```
% `List` module is required
@require: list

...

+math(
  let-math \stack-lower m msublst =
    msublst |> List.fold-left math-lower m
  in
  ${
  \sum_{i=1}^n i^2
  = k^2 + \lower{\sum_{i=1}^n}{i\neq k} i^2
  = k^2 + \stack-lower{\sum^n}{| i = 1 | i\neq k |} i^2
  = j^2 + k^2 + \stack-lower{\sum^n}{| i = 1 | i\neq j | i\neq k |} i^2
  });
```

![math-example.png](https://user-images.githubusercontent.com/48883418/97694449-ee227280-1ae5-11eb-9d28-33be0191b454.png)

**Comment by TonalidadeHidrica** [comment]
Thank you.  So, I had to apply `lower` outside the sigma, instead of applying inside `_{ }`.  Now it works, thanks.

![image](https://user-images.githubusercontent.com/47710717/97699962-5d03c980-1aee-11eb-8ccc-94fbc57f6be1.png)

```
@require: stdjabook
@require: list
  let-math \stack-lower m msublst =
    msublst |> List.fold-left math-lower m
  in

document (|
  title = {\SATySFi; Playground};
  author = {Your Name};
  show-title = true;
  show-toc = false;
|) '<
    +p {
        \align[
             ${| \sum_{i = 1}^n i^2 |};
             ${| \sum_{\lower{i=1}{i \neq j}}^n i^2 |};
             ${| \lower{\sum_{i=1}^n}{i \neq j} i^2 |};
             ${| \stack-lower{\sum^n}{| i = 1 | i\neq j |} i^2 |};
        ];
    }
>
```

By the way, isn't it possible to expand the grammar in the future so that we can someday use something like `\sum_{| i=1 | i\neq j |}^n` ?  It'd be more concise and useful.

**Comment by monaqa** [comment]
It may be technically possible, but I doubt the formula `a_{| b | c |}` is used often enough to be specified as the SATySFi's grammar.
(This is just one user's opinion, and the decision on how to extend SATySFi's grammar should be made by the lead maintainer, @gfngfn .)

**Comment by na4zagin3** [comment]
Just my two cents, that could be a use case of ad hoc polymorphism when it is introduced to SATySFi.

**Comment by TonalidadeHidrica** [comment]
Current SaTysFi system does not accept two different types as an argument right?
