### ISSUE TITLE
I want to be able to set up a document information dictionary.

### ISSUE THREAD

**Issue by puripuri2100** [gfngfn/SATySFi#267]
Now, there is no information dictionary in the PDF file output by SATySFi.

<img width="560" alt="fig" src="https://user-images.githubusercontent.com/36466996/115134482-6a385480-a04b-11eb-9c4b-a91f8778f6e2.PNG">

I want to be able to set up a document information dictionary.

I'm thinking of code like this:

```ocaml
let () = set-information-dictionary (|
  title = Some(`title`);
  subjects = Some(`subject`);
  keywords = [`keyword`];
  author = Some(`author`);
|)
```

**Comment by gfngfn** [comment]
I understand what you want to do. It seems worth implementing to me as well :+1:

According to *PDF Reference sixth edition*, Sections 3.4.4 and 10.2.1, the document information dictionary is supposed to be contained in the trailer dictionary by using `/Info` key. Based on the API of `camlpdf`, we can realize this functionality by modifying `trailerdict` field of values of type `Pdf.t`.

The formalization of `set-information-dictionary` looks, however, too imperative to me. Intuitively, an optional argument of page-breaking primitives seems to be a suitable place for such settings:

```
val page-break : ?(| title : string option; … |) -> …
```
