### ISSUE TITLE
Math expressions with primes, superscripts, and subscripts are sometimes parsed wrong

### ISSUE THREAD

**Issue by TonalidadeHidrica** [gfngfn/SATySFi#274]
I guess all of the following notation should be allowed:

```saty
@require: stdjareport

document (| title = {}; author = {} |) '<
  +p {
    ${a}
    ${a^1}
    ${a_2}
    ${a_2^1}
    ${a^1_2}
    ${a'}
    ${a'^1}
    ${a'_2}
    % ${a'_2^1}
    % ${a'^1_2}
  }
>
```

However, the last two patterns are not allowed, and the fourth last one is typeset wrong, like this:

![image](https://user-images.githubusercontent.com/47710717/119235847-5a8ebd00-bb6f-11eb-9193-01257cc47709.png)

Is this a bug or an intended behaviour?

**Comment by TonalidadeHidrica** [comment]
I think one of the reason is that [`mathtop` rule of `src/frontend/parser.mly`](https://github.com/gfngfn/SATySFi/blob/master/src/frontend/parser.mly#L1078-L1109) is not exhaustive.  (BTW I wonder why they are ordered in such a random manner...)

**Comment by TonalidadeHidrica** [comment]
@leque The issue of the unallowed patterns are a duplicate of #94 (which I didn't know up until now), and you mentioned in #298 that the wrong type set is corrected by 0404981e3be2bb3bf4a7e65a3e8154ac83713fae , so can I safely close this issue?

**Comment by leque** [comment]
@TonalidadeHidrica Sorry for late reply. #298 is merged now. Could you check the PR resolves this issue?

**Comment by TonalidadeHidrica** [comment]
The issue was resolved!!  Thanks for your fix.

**Comment by TonalidadeHidrica** [comment]
And sorry for late reply, too.
