### ISSUE TITLE
How about releasing v0.0.7

### ISSUE THREAD

**Issue by puripuri2100** [gfngfn/SATySFi#321]
It has been a year since [the last release](https://github.com/gfngfn/SATySFi/releases/tag/v0.0.6).
There are many unreleased changes.
The value of being able to use these features is enormous.

**Comment by monaqa** [comment]
Agreed.
There are two commits pending release of the tools I maintain. Both relate to Unicode support in math mode.

- https://github.com/monaqa/satysfi-parser/pull/9
  - This PR will improve the behavior of the satysfi language server.
- https://github.com/monaqa/satysfi-azmath/tree/feat/unicode_math

Once v0.0.7 is released, we can officially offer these new features.

**Comment by puripuri2100** [comment]
done: #324
