### ISSUE TITLE
Awkward spacing at the beggining of a math equation

### ISSUE THREAD

**Issue by sankantsu** [gfngfn/SATySFi#332]
When you write a binary operator (such like `+` or `-`) at the beggining of a math equation, the spacing between binary operator and the following number looks awkward.

For example, this code shows this awkward spacing.

```
@require: stdjareport

document (|
    title = {Awkward spacing at the begging of math};
    author = {sankantsu};
|) '<
     +p {
         ${+1 - 2 = -1}
     }
>
```

As a user-level solution, you can avoid this spacing problem by defining a math-command to treat `+` or `-` as MathOrd class using `math-char` primitive and use this command at the beggining of the equation.

I think when a `+` or `-` symbol is put at the beggining of a math equation it is usually intended to be an unary operator for the following number.

I don't know whether this behavior of the SATySFi is intentional or not, but TeX seems to be treating binary operators at the beggining of a equation as a Ord symbol and I prefer TeX's approach.

It seems that very small change to the source code fix this problem.
Please consider changing this spacing behavior.

**Comment by gfngfn** [comment]
Merged #333. Thank you!
