### ISSUE TITLE
Switch from uCoreLib to uucp and utext

### ISSUE THREAD

**Issue by objmagic** [gfngfn/SATySFi#40]
Daniel just released his another Unicode library: https://github.com/dbuenzli/utext

As a side note, I recommend using packages used by [Mirage organization](https://github.com/mirage) or packages developed by people from OCaml Labs since those packages are **well documented** and **well maintained**

**Comment by objmagic** [comment]
seems uCoreLib depends on `bitv` which depends on `autoconf` which caused the trouble in https://github.com/gfngfn/SATySFi/issues/35

**Comment by nekketsuuu** [comment]
Indeed, the author of uCoreLib says he doesn't develop it anymore, and recommends to use his newer module, [Camomile](https://github.com/yoriyuki/Camomile). See yoriyuki/ucorelib#9.

I don't know which alternative is better, but an replacement is needed.
