### ISSUE TITLE
Travis started to fail

### ISSUE THREAD

**Issue by qnighy** [gfngfn/SATySFi#46]
Currently #44 ([build #929](https://travis-ci.org/gfngfn/SATySFi/builds/347738475)) and #45 ([build #930](https://travis-ci.org/gfngfn/SATySFi/builds/348081919)) fail (for seemingly the same reasons). As #44 is a trivial change, they must be spurious errors.

I couldn't figure out the exact cause. Seems to be related to `core_kernel`.

**Comment by mt-caret** [comment]
I get the same error message as https://travis-ci.org/gfngfn/SATySFi/builds/348081919 while packaging SATySFi for Nix; I would love to know how to fix it.

Logs:
https://gist.github.com/mt-caret/26689bcc94a81274081ff3927fa1d9c5

I'm at 042a8aaf3b61785b8edac7d799067ad758ed2fd7 and I'm getting this error since 26aa766d49ddc297741d72ddb2ba8d40457cc61c so the error might be originating somewhere else...

**Comment by qnighy** [comment]
I tried to bisect `dune` (formerly `jbuilder`) between `1.0+beta17` and `1.0+beta18` with the following test script:

```sh
opam reinstall -y jbuilder
opam reinstall -y core_kernel
```

Bisect reported ocaml/dune@9e4cc843704262b3cb563096ae7df128d0ea2bff as the first bad commit.

**Comment by mt-caret** [comment]
I can confirm, https://github.com/gfngfn/SATySFi/pull/47 indeed fixes the error. Thank you!

An upstream bug, then?

**Comment by qnighy** [comment]
Probably. I'm investigating further.

**Comment by qnighy** [comment]
The bisect procedure above was wrong; now I pinned `jbuilder` and `satysfi` to local repos and bisected on `jbuilder` with the following script:

```sh
opam reinstall -y jbuilder
opam reinstall -y core_kernel
opam reinstall -y satysfi
```

Bisect reported ocaml/dune@b3838284c6f28aaa0afabf865ce126c20e2f3616 as the first bad commit.

**Comment by mt-caret** [comment]
There's a PR that might be addressing the issue: https://github.com/ocaml/dune/issues/567

**Comment by qnighy** [comment]
Confirmed locally that the current master (ocaml/dune@e4aac2da97c069a914c9fb6c06697b5a99145d17) does not cause the `Core_kernel__` problem. I think it is good to pin to `1.0+beta17` until `1.0+beta19` is released.
