### ISSUE TITLE
Pushing back patches of external dependencies

### ISSUE THREAD

**Issue by qnighy** [gfngfn/SATySFi#61]
Is there a plan to push patches in [gfngfn/camlpdf](https://github.com/gfngfn/camlpdf) and [gfngfn/otfm](https://github.com/gfngfn/otfm) back to their upstreams, [johnwhitington/camlpdf](https://github.com/johnwhitington/camlpdf) and [dbuenzli/otfm](https://github.com/dbuenzli/otfm)? I can help preparing PRs.

**Comment by nekketsuuu** [comment]
Related: #14

**Comment by qnighy** [comment]
OK, its a kind of dupe. Closing.
