### ISSUE TITLE
Broken embedded text information

### ISSUE THREAD

**Issue by qnighy** [gfngfn/SATySFi#64]
The current version of SATySFi doesn't correctly produce embedded texts (i.e. information used when copying or searching on PDF viewers). This is a known issue, which is caused by lack of the `/ToUnicode` entry.

**Comment by gfngfn** [comment]
Fixed by [this commit](https://github.com/gfngfn/SATySFi/commit/46592d42d472654a622e8fff45449b7285ea40a4).
